[theme]
base="system"
backgroundColor="ghostWhite"
secondaryBackgroundColour="powderBlue"
textColor="black"
baseRadius="full"
borderColor="mediumSlateBlue"

[theme.sidebar]
backgroundColor="ghostWhite"
secondaryBackgroundColor="lavender"
